### ISSUE TITLE
plot to visualise fixed and random effects breaks with 3+ covariates

### ISSUE THREAD

**Issue by ianjonsen** [ianjonsen/mpmm#1]
plot() code is not properly generalised to all fixed-random effect combinations. testing required to see if issue is with the fixed or random code sections (or both). Plot seems to work as intended for <= 2 covariates 

![plot_broken](https://user-images.githubusercontent.com/9984184/37052790-6fd30d94-21ce-11e8-8001-2e39f85838bb.jpeg)

**Comment by jamesgrecian** [comment]
plot() works with 3 covariates fitted as random slopes but not as random intercepts
`fit <- mpmm(~ ice + bathy + sal_diff + (ice + bathy + sal_diff | id), data = ellie.ice)`
`plot(fit)`
![Rplot](https://user-images.githubusercontent.com/34245401/84906380-bfad7900-b0a9-11ea-9014-4dc1d24a923c.jpeg)

**Comment by ianjonsen** [comment]
thanks @jamesgrecian. was this using the dev_4_james version?

**Comment by jamesgrecian** [comment]
That was using `mpmm_0.1.5.9800` with R version 3.6.1 (2019-07-05)

**Comment by ianjonsen** [comment]
revised `plot()` with 3 covariates fitted as random slopes
![Rplot](https://user-images.githubusercontent.com/9984184/85640640-bc465e80-b662-11ea-921e-19d445ebdefa.png)

and with 3 covariates fitted with random intercepts
![Rplot01](https://user-images.githubusercontent.com/9984184/85640742-00d1fa00-b663-11ea-8663-b3630a2bedba.png)

**Comment by ianjonsen** [comment]
3 covariates with random intercepts and labelled by id, `plot(m, label = TRUE)`
![Rplot](https://user-images.githubusercontent.com/9984184/85640996-b4d38500-b663-11ea-8420-6514706b89a5.png)

**Comment by ianjonsen** [comment]
issue fixed in dev_4_james branch, will merge with master in Sept. closing this now
